/* eslint-disable */
// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: 'poc-archiver-expo',
  DISPLAY_NAME: 'ExpoPOC',
  DESCRIPTION: 'ReactNative Expo SDK POC collection',
  REPOSITORY: 'https://github.com/amwebexpert/poc-archiver-expo',
  AUTHOR: 'amwebexpert@gmail.com',
  VERSION: '1.3.0',
  VERSION_DATE: '2025-02-22',
  VERSION_DATE_ISO: '2025-02-22T16:32:42.648Z',
})

export const LONG_VERSION_DATE = '1.3.0 (2025-02-22)'
